### ISSUE TITLE
Issues and suggestions

### ISSUE THREAD

**Issue by iorbita** [micker/mod_dashboard#15]
Hello,
here are issues I identified in this latest version.

**Issues**

- Blocks display just one item despite the setting to 10 items
- Blocks are displayed in a single column (you can solve the problem with a simple flex rule)
- "Unauthorized" items are still displayed inside blocks

**Suggestions**

- Be able to name several custom tabs (as is the case for free tab).
- Be able to order buttons in custom tabs.

**Question**

In "Free" tab, how component/module link should be write?

Thank you,

Lorenzo

**Comment by micker** [comment]
hello can you more precise ?
issues
1 basic blocks (published trashed etc..) or custom block with specific catagorie
2 did you change value (44 instead of 45 for width)
3 idem be more precise you mean via acl ?

Suggestions
1 not be possible for now but with repetable field of j4 i hope i can acheive this
2 not be sure to understand ...
 
Question
use relative path like
index.php?action.....

**Comment by iorbita** [comment]
Hello,
**Issues**
1. I’m referring to custom blocks with specific categories
2. I tried with different dimensions and blocks remain on a single column
3. Yes I’m referring to acl settings. If an article is unauthorized I can’t edit it, but it remains visible in the block. This is not the case in Joomla core articles list, if an article is unauthorized it is also not visible in the article list.

Thank you,

Lorenzo

**Comment by micker** [comment]
ok can you provide link for test more ?
